/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse;

import javax.swing.JOptionPane;

/**
 *
 * @author Raymond
 */
public class NieuweSpeler extends javax.swing.JFrame {

    /**
     * Creates new form Inschrijving
     */
    public NieuweSpeler() {
        initComponents();
        jl_voornaamError.setVisible(false);
        jl_achternaamError.setVisible(false);
        jl_woonplaatsError.setVisible(false);
        jl_postcodeError.setVisible(false);
        jl_telefoonNummerError.setVisible(false);
        jl_emailadresError.setVisible(false);
        jl_toernooiCodeErrorNS.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_voornaam = new javax.swing.JLabel();
        tf_voornaam = new javax.swing.JTextField();
        jl_achternaam = new javax.swing.JLabel();
        tf_achternaam = new javax.swing.JTextField();
        jl_adres = new javax.swing.JLabel();
        tf_adres = new javax.swing.JTextField();
        jl_postcode = new javax.swing.JLabel();
        tf_postcode = new javax.swing.JTextField();
        jl_woonplaats = new javax.swing.JLabel();
        tf_woonplaats = new javax.swing.JTextField();
        jl_telefoonNummer = new javax.swing.JLabel();
        tf_telefoonNummer = new javax.swing.JTextField();
        jl_emailAdres = new javax.swing.JLabel();
        tf_emailAdres = new javax.swing.JTextField();
        jl_toernooiCodeNS = new javax.swing.JLabel();
        tf_toernooiCodeNS = new javax.swing.JTextField();
        jb_inschrijvenToernooi = new javax.swing.JButton();
        jb_toernooiZoeken = new javax.swing.JButton();
        jb_spelerZoeken = new javax.swing.JButton();
        jb_inschrijvenMasterclass = new javax.swing.JButton();
        jl_voornaamError = new javax.swing.JLabel();
        jl_achternaamError = new javax.swing.JLabel();
        jl_woonplaatsError = new javax.swing.JLabel();
        jl_postcodeError = new javax.swing.JLabel();
        jl_telefoonNummerError = new javax.swing.JLabel();
        jl_emailadresError = new javax.swing.JLabel();
        jl_toernooiCodeErrorNS = new javax.swing.JLabel();
        jb_test = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(364, 400));
        setResizable(false);

        jl_voornaam.setText("Voornaam            :");

        tf_voornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_voornaamKeyReleased(evt);
            }
        });

        jl_achternaam.setText("Achternaam        :");

        tf_achternaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_achternaamKeyReleased(evt);
            }
        });

        jl_adres.setText("Adres                  :");

        tf_adres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_adresKeyReleased(evt);
            }
        });

        jl_postcode.setText("Postcode             :");

        tf_postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_postcodeKeyReleased(evt);
            }
        });

        jl_woonplaats.setText("Woonplaats         :");

        tf_woonplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_woonplaatsActionPerformed(evt);
            }
        });
        tf_woonplaats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_woonplaatsKeyReleased(evt);
            }
        });

        jl_telefoonNummer.setText("Telefoonnummer :");

        tf_telefoonNummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_telefoonNummerKeyReleased(evt);
            }
        });

        jl_emailAdres.setText(" Emailadres          :");

        tf_emailAdres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emailAdresKeyReleased(evt);
            }
        });

        jl_toernooiCodeNS.setText("Toernooicode      :");

        jb_inschrijvenToernooi.setText("Inschrijven toernooi");
        jb_inschrijvenToernooi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_inschrijvenToernooiActionPerformed(evt);
            }
        });

        jb_toernooiZoeken.setText("Toernooi zoeken");

        jb_spelerZoeken.setText("Speler zoeken");

        jb_inschrijvenMasterclass.setText("Inschrijven Masterclass");

        jl_voornaamError.setForeground(new java.awt.Color(255, 0, 0));
        jl_voornaamError.setText("Alleen letters toegestaan");

        jl_achternaamError.setForeground(new java.awt.Color(255, 0, 0));
        jl_achternaamError.setText("Alleen letters toegestaan");

        jl_woonplaatsError.setForeground(new java.awt.Color(255, 0, 0));
        jl_woonplaatsError.setText("Alleen letters toegestaan");

        jl_postcodeError.setForeground(new java.awt.Color(255, 0, 0));
        jl_postcodeError.setText("Voorbeeld: 1234AB");

        jl_telefoonNummerError.setForeground(new java.awt.Color(255, 0, 0));
        jl_telefoonNummerError.setText("Vul een geldig telefoonnummer in");

        jl_emailadresError.setForeground(new java.awt.Color(255, 0, 0));
        jl_emailadresError.setText("Ongeldig email adres");

        jl_toernooiCodeErrorNS.setForeground(new java.awt.Color(255, 0, 0));
        jl_toernooiCodeErrorNS.setText("Voer alleen cijfers in");

        jb_test.setText("Test");
        jb_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_testActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jl_postcode))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_emailAdres)
                                    .addComponent(jl_toernooiCodeNS)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jl_telefoonNummer))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jl_woonplaats))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jl_adres))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jl_achternaam))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jl_voornaam)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jl_voornaamError))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_achternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jl_achternaamError))
                            .addComponent(tf_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_woonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_emailAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_telefoonNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_toernooiCodeNS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_toernooiCodeErrorNS)
                                    .addComponent(jl_emailadresError)
                                    .addComponent(jl_telefoonNummerError)
                                    .addComponent(jl_postcodeError)
                                    .addComponent(jl_woonplaatsError)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_inschrijvenToernooi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_inschrijvenMasterclass))
                        .addGap(82, 82, 82)
                        .addComponent(jb_test)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_spelerZoeken, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_toernooiZoeken))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jl_voornaamError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_achternaamError))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_voornaam)
                            .addComponent(tf_voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_achternaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_achternaam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_adres))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_postcode)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_woonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_woonplaatsError)
                            .addComponent(jl_woonplaats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_postcodeError))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_telefoonNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_telefoonNummer)))
                    .addComponent(jl_telefoonNummerError, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_emailAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_emailAdres)
                    .addComponent(jl_emailadresError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_toernooiCodeNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_toernooiCodeNS)
                    .addComponent(jl_toernooiCodeErrorNS))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_inschrijvenToernooi)
                            .addComponent(jb_spelerZoeken))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_inschrijvenMasterclass)
                            .addComponent(jb_toernooiZoeken)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jb_test))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_woonplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_woonplaatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_woonplaatsActionPerformed

    private void tf_voornaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_voornaamKeyReleased
        String voornaam = tf_voornaam.getText();
        if (voornaam.matches("[^0-9]{0,20}")) {
            jl_voornaamError.setVisible(false);
        }
        else    {
            jl_voornaamError.setVisible(true);
        }   
    }//GEN-LAST:event_tf_voornaamKeyReleased

    private void tf_achternaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_achternaamKeyReleased
        String achternaam = tf_achternaam.getText();
        if (achternaam.matches("[^0-9]{0,20}")) {
            jl_achternaamError.setVisible(false);
            
        }
        else    {
            jl_achternaamError.setVisible(true);
        }
    }//GEN-LAST:event_tf_achternaamKeyReleased

    private void tf_adresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_adresKeyReleased

    }//GEN-LAST:event_tf_adresKeyReleased

    private void tf_woonplaatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_woonplaatsKeyReleased
        String woonplaats = tf_woonplaats.getText();
        if (woonplaats.matches("[^0-9]{0,45}")) {
            jl_woonplaatsError.setVisible(false);
            
        }
        else    {
            jl_woonplaatsError.setVisible(true);
        }
    }//GEN-LAST:event_tf_woonplaatsKeyReleased

    private void tf_postcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_postcodeKeyReleased
        String postcode = tf_postcode.getText();
        if (postcode.matches("[0-9]{4}[a-zA-Z]{2}")) {
            jl_postcodeError.setVisible(false);
            
        }
        else    {
            jl_postcodeError.setVisible(true);
        }
    }//GEN-LAST:event_tf_postcodeKeyReleased

    private void tf_telefoonNummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_telefoonNummerKeyReleased
        String telefoonNummer = tf_telefoonNummer.getText();
        if (telefoonNummer.matches("[0-9]{0,11}")) {
            jl_telefoonNummerError.setVisible(false);
            
        }
        else    {
            jl_telefoonNummerError.setVisible(true);
        }
    }//GEN-LAST:event_tf_telefoonNummerKeyReleased

    private void tf_emailAdresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emailAdresKeyReleased
                    String emailAdres = tf_emailAdres.getText();
        if (emailAdres.contains("@") && emailAdres.contains(".")) {
            jl_emailadresError.setVisible(false);
                  }
        else    {
            jl_emailadresError.setVisible(true);
        }
    }//GEN-LAST:event_tf_emailAdresKeyReleased

    private void jb_inschrijvenToernooiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_inschrijvenToernooiActionPerformed
        Persoon nieuwePersoon = new Persoon();
        
        String voornaam = tf_voornaam.getText();
        String achternaam = tf_achternaam.getText();
        String adres = tf_adres.getText();
        String woonplaats = tf_woonplaats.getText();
        String postcode = tf_postcode.getText();
        String telefoonNummer = tf_telefoonNummer.getText();
        String emailAdres = tf_emailAdres.getText();
        int telefoonNummerInt = Integer.parseInt(telefoonNummer);
        
        nieuwePersoon.persoonToevoegen(voornaam, achternaam, adres, woonplaats, postcode, telefoonNummerInt, emailAdres);
        JOptionPane.showMessageDialog(rootPane, "Toevoegen voltooid!");
        
    }//GEN-LAST:event_jb_inschrijvenToernooiActionPerformed

    private void jb_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_testActionPerformed
        Persoon test = new Persoon();
        test.pCode();
    }//GEN-LAST:event_jb_testActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NieuweSpeler().setVisible(true);
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_inschrijvenMasterclass;
    private javax.swing.JButton jb_inschrijvenToernooi;
    private javax.swing.JButton jb_spelerZoeken;
    private javax.swing.JButton jb_test;
    private javax.swing.JButton jb_toernooiZoeken;
    private javax.swing.JLabel jl_achternaam;
    private javax.swing.JLabel jl_achternaamError;
    private javax.swing.JLabel jl_adres;
    private javax.swing.JLabel jl_emailAdres;
    private javax.swing.JLabel jl_emailadresError;
    private javax.swing.JLabel jl_postcode;
    private javax.swing.JLabel jl_postcodeError;
    private javax.swing.JLabel jl_telefoonNummer;
    private javax.swing.JLabel jl_telefoonNummerError;
    private javax.swing.JLabel jl_toernooiCodeErrorNS;
    private javax.swing.JLabel jl_toernooiCodeNS;
    private javax.swing.JLabel jl_voornaam;
    private javax.swing.JLabel jl_voornaamError;
    private javax.swing.JLabel jl_woonplaats;
    private javax.swing.JLabel jl_woonplaatsError;
    private javax.swing.JTextField tf_achternaam;
    private javax.swing.JTextField tf_adres;
    private javax.swing.JTextField tf_emailAdres;
    private javax.swing.JTextField tf_postcode;
    private javax.swing.JTextField tf_telefoonNummer;
    private javax.swing.JTextField tf_toernooiCodeNS;
    private javax.swing.JTextField tf_voornaam;
    private javax.swing.JTextField tf_woonplaats;
    // End of variables declaration//GEN-END:variables
}
