/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse;

import javax.swing.JOptionPane;

/**
 *
 * @author Raymond
 */
public class NieuweSpeler extends javax.swing.JFrame {

    /**
     * Creates new form Inschrijving
     */
    private boolean betaaldBoolean = false;
    
    public NieuweSpeler() {
        initComponents();
        jl_voornaamError.setVisible(false);
        jl_achternaamError.setVisible(false);
        jl_woonplaatsError.setVisible(false);
        jl_postcodeError.setVisible(false);
        jl_telefoonNummerError.setVisible(false);
        jl_emailadresError.setVisible(false);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_voornaam = new javax.swing.JLabel();
        tf_voornaam = new javax.swing.JTextField();
        jl_achternaam = new javax.swing.JLabel();
        tf_achternaam = new javax.swing.JTextField();
        jl_adres = new javax.swing.JLabel();
        tf_adres = new javax.swing.JTextField();
        jl_postcode = new javax.swing.JLabel();
        tf_postcode = new javax.swing.JTextField();
        jl_woonplaats = new javax.swing.JLabel();
        tf_woonplaats = new javax.swing.JTextField();
        jl_telefoonNummer = new javax.swing.JLabel();
        tf_telefoonNummer = new javax.swing.JTextField();
        jl_emailAdres = new javax.swing.JLabel();
        tf_emailAdres = new javax.swing.JTextField();
        jb_inschrijven = new javax.swing.JButton();
        jb_toernooiZoeken = new javax.swing.JButton();
        jb_spelerZoeken = new javax.swing.JButton();
        jl_voornaamError = new javax.swing.JLabel();
        jl_achternaamError = new javax.swing.JLabel();
        jl_woonplaatsError = new javax.swing.JLabel();
        jl_postcodeError = new javax.swing.JLabel();
        jl_telefoonNummerError = new javax.swing.JLabel();
        jl_emailadresError = new javax.swing.JLabel();
        jb_cancel = new javax.swing.JButton();
        jb_masterclassZoeken = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 400));
        setPreferredSize(new java.awt.Dimension(650, 356));

        jl_voornaam.setText("Voornaam :");

        tf_voornaam.setMinimumSize(new java.awt.Dimension(125, 20));
        tf_voornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_voornaamKeyReleased(evt);
            }
        });

        jl_achternaam.setText("Achternaam :");

        tf_achternaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_achternaamKeyReleased(evt);
            }
        });

        jl_adres.setText("Adres :");

        tf_adres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_adresKeyReleased(evt);
            }
        });

        jl_postcode.setText("Postcode :");

        tf_postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_postcodeKeyReleased(evt);
            }
        });

        jl_woonplaats.setText("Woonplaats :");

        tf_woonplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_woonplaatsActionPerformed(evt);
            }
        });
        tf_woonplaats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_woonplaatsKeyReleased(evt);
            }
        });

        jl_telefoonNummer.setText("Telefoonnummer :");

        tf_telefoonNummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_telefoonNummerKeyReleased(evt);
            }
        });

        jl_emailAdres.setText(" Emailadres :");

        tf_emailAdres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emailAdresKeyReleased(evt);
            }
        });

        jb_inschrijven.setText("Inschrijven");
        jb_inschrijven.setMaximumSize(new java.awt.Dimension(100, 23));
        jb_inschrijven.setMinimumSize(new java.awt.Dimension(100, 23));
        jb_inschrijven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_inschrijvenActionPerformed(evt);
            }
        });

        jb_toernooiZoeken.setText("Toernooi zoeken");
        jb_toernooiZoeken.setMaximumSize(new java.awt.Dimension(100, 23));
        jb_toernooiZoeken.setMinimumSize(new java.awt.Dimension(100, 23));
        jb_toernooiZoeken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_toernooiZoekenActionPerformed(evt);
            }
        });

        jb_spelerZoeken.setText("Speler zoeken");
        jb_spelerZoeken.setMaximumSize(new java.awt.Dimension(100, 23));
        jb_spelerZoeken.setMinimumSize(new java.awt.Dimension(100, 23));
        jb_spelerZoeken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_spelerZoekenActionPerformed(evt);
            }
        });

        jl_voornaamError.setForeground(new java.awt.Color(255, 0, 0));
        jl_voornaamError.setText("Alleen letters toegestaan");

        jl_achternaamError.setForeground(new java.awt.Color(255, 0, 0));
        jl_achternaamError.setText("Alleen letters toegestaan");

        jl_woonplaatsError.setForeground(new java.awt.Color(255, 0, 0));
        jl_woonplaatsError.setText("Alleen letters toegestaan");

        jl_postcodeError.setForeground(new java.awt.Color(255, 0, 0));
        jl_postcodeError.setText("Voorbeeld: 1234AB");

        jl_telefoonNummerError.setForeground(new java.awt.Color(255, 0, 0));
        jl_telefoonNummerError.setText("Vul een geldig telefoonnummer in");

        jl_emailadresError.setForeground(new java.awt.Color(255, 0, 0));
        jl_emailadresError.setText("Ongeldig email adres");

        jb_cancel.setText("Cancel");
        jb_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelActionPerformed(evt);
            }
        });

        jb_masterclassZoeken.setText("Masterclass Zoeken");
        jb_masterclassZoeken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_masterclassZoekenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_voornaam)
                            .addComponent(jl_adres)
                            .addComponent(jl_achternaam)
                            .addComponent(jl_telefoonNummer)
                            .addComponent(jl_woonplaats)
                            .addComponent(jl_postcode)
                            .addComponent(jl_emailAdres))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jl_postcodeError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jb_cancel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(tf_voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jl_voornaamError))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(tf_achternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jl_achternaamError))
                                            .addComponent(tf_adres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jb_masterclassZoeken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jb_spelerZoeken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jb_toernooiZoeken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tf_woonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jl_woonplaatsError))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tf_emailAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jl_emailadresError))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tf_telefoonNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jl_telefoonNummerError)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_inschrijven, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_voornaam)
                    .addComponent(tf_voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_voornaamError)
                    .addComponent(jb_toernooiZoeken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_achternaam)
                    .addComponent(tf_achternaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_achternaamError)
                    .addComponent(jb_spelerZoeken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_adres)
                    .addComponent(tf_adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_masterclassZoeken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_woonplaats)
                    .addComponent(tf_woonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_woonplaatsError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_postcode)
                    .addComponent(tf_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_postcodeError))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jl_telefoonNummerError))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_telefoonNummer)
                            .addComponent(tf_telefoonNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_emailAdres)
                    .addComponent(tf_emailAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_emailadresError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cancel)
                    .addComponent(jb_inschrijven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_woonplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_woonplaatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_woonplaatsActionPerformed

    private void tf_voornaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_voornaamKeyReleased
        String voornaam = tf_voornaam.getText();
        if (voornaam.matches("[^0-9]{0,20}")) {
            jl_voornaamError.setVisible(false);
        }
        else    {
            jl_voornaamError.setVisible(true);
        }   
    }//GEN-LAST:event_tf_voornaamKeyReleased

    private void tf_achternaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_achternaamKeyReleased
        String achternaam = tf_achternaam.getText();
        if (achternaam.matches("[^0-9]{0,20}")) {
            jl_achternaamError.setVisible(false);
            
        }
        else    {
            jl_achternaamError.setVisible(true);
        }
    }//GEN-LAST:event_tf_achternaamKeyReleased

    private void tf_adresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_adresKeyReleased

    }//GEN-LAST:event_tf_adresKeyReleased

    private void tf_woonplaatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_woonplaatsKeyReleased
        String woonplaats = tf_woonplaats.getText();
        if (woonplaats.matches("[^0-9]{0,45}")) {
            jl_woonplaatsError.setVisible(false);
            
        }
        else    {
            jl_woonplaatsError.setVisible(true);
        }
    }//GEN-LAST:event_tf_woonplaatsKeyReleased

    private void tf_postcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_postcodeKeyReleased
        String postcode = tf_postcode.getText();
        if (postcode.matches("[0-9]{4}[a-zA-Z]{2}")) {
            jl_postcodeError.setVisible(false);
            
        }
        else    {
            jl_postcodeError.setVisible(true);
        }
    }//GEN-LAST:event_tf_postcodeKeyReleased

    private void tf_telefoonNummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_telefoonNummerKeyReleased
        String telefoonNummer = tf_telefoonNummer.getText();
        if (telefoonNummer.matches("[0-9]{10}")) {
            jl_telefoonNummerError.setVisible(false);
            
        }
        else    {
            jl_telefoonNummerError.setVisible(true);
        }
    }//GEN-LAST:event_tf_telefoonNummerKeyReleased

    private void tf_emailAdresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emailAdresKeyReleased
                    String emailAdres = tf_emailAdres.getText();
        if (emailAdres.contains("@") && emailAdres.contains(".")) {
            jl_emailadresError.setVisible(false);
                  }
        else    {
            jl_emailadresError.setVisible(true);
        }
    }//GEN-LAST:event_tf_emailAdresKeyReleased

    private void jb_inschrijvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_inschrijvenActionPerformed
  
        Persoon nieuwePersoon = new Persoon();
        
        String voornaam = tf_voornaam.getText();
        String achternaam = tf_achternaam.getText();
        String adres = tf_adres.getText();
        String woonplaats = tf_woonplaats.getText();
        String postcode = tf_postcode.getText();
        String telefoonNummer = tf_telefoonNummer.getText();
        String emailAdres = tf_emailAdres.getText();
        int telefoonNummerInt = Integer.parseInt(telefoonNummer);
        
        nieuwePersoon.persoonToevoegen(voornaam, achternaam, adres, woonplaats, postcode, telefoonNummerInt, emailAdres);
        JOptionPane.showMessageDialog(rootPane, "Toevoegen voltooid!");
        
    }//GEN-LAST:event_jb_inschrijvenActionPerformed

    private void jb_spelerZoekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_spelerZoekenActionPerformed
        SpelerZoeken spelerZoeken = new SpelerZoeken();
        spelerZoeken.setVisible(true);
    }//GEN-LAST:event_jb_spelerZoekenActionPerformed

    private void jb_toernooiZoekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_toernooiZoekenActionPerformed
        Toernooi toernooiZoeken = new Toernooi();
        toernooiZoeken.setVisible(true);
    }//GEN-LAST:event_jb_toernooiZoekenActionPerformed

    private void jb_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jb_cancelActionPerformed

    private void jb_masterclassZoekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_masterclassZoekenActionPerformed
        Masterclass mc = new Masterclass();
        mc.setVisible(true);
    }//GEN-LAST:event_jb_masterclassZoekenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NieuweSpeler().setVisible(true);
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_cancel;
    private javax.swing.JButton jb_inschrijven;
    private javax.swing.JButton jb_masterclassZoeken;
    private javax.swing.JButton jb_spelerZoeken;
    private javax.swing.JButton jb_toernooiZoeken;
    private javax.swing.JLabel jl_achternaam;
    private javax.swing.JLabel jl_achternaamError;
    private javax.swing.JLabel jl_adres;
    private javax.swing.JLabel jl_emailAdres;
    private javax.swing.JLabel jl_emailadresError;
    private javax.swing.JLabel jl_postcode;
    private javax.swing.JLabel jl_postcodeError;
    private javax.swing.JLabel jl_telefoonNummer;
    private javax.swing.JLabel jl_telefoonNummerError;
    private javax.swing.JLabel jl_voornaam;
    private javax.swing.JLabel jl_voornaamError;
    private javax.swing.JLabel jl_woonplaats;
    private javax.swing.JLabel jl_woonplaatsError;
    private javax.swing.JTextField tf_achternaam;
    private javax.swing.JTextField tf_adres;
    private javax.swing.JTextField tf_emailAdres;
    private javax.swing.JTextField tf_postcode;
    private javax.swing.JTextField tf_telefoonNummer;
    private javax.swing.JTextField tf_voornaam;
    private javax.swing.JTextField tf_woonplaats;
    // End of variables declaration//GEN-END:variables
}
