/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse;

import javax.swing.JOptionPane;

/**
 *
 * @author Raymond
 */
public class NieuweSpeler extends javax.swing.JFrame {

    /**
     * Creates new form Inschrijving
     */
    private boolean betaaldBoolean = false;
    
    public NieuweSpeler() {
        initComponents();
        jl_voornaamError.setVisible(false);
        jl_achternaamError.setVisible(false);
        jl_woonplaatsError.setVisible(false);
        jl_postcodeError.setVisible(false);
        jl_telefoonNummerError.setVisible(false);
        jl_emailadresError.setVisible(false);
        jl_toernooiCodeErrorNS.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_voornaam = new javax.swing.JLabel();
        tf_voornaam = new javax.swing.JTextField();
        jl_achternaam = new javax.swing.JLabel();
        tf_achternaam = new javax.swing.JTextField();
        jl_adres = new javax.swing.JLabel();
        tf_adres = new javax.swing.JTextField();
        jl_postcode = new javax.swing.JLabel();
        tf_postcode = new javax.swing.JTextField();
        jl_woonplaats = new javax.swing.JLabel();
        tf_woonplaats = new javax.swing.JTextField();
        jl_telefoonNummer = new javax.swing.JLabel();
        tf_telefoonNummer = new javax.swing.JTextField();
        jl_emailAdres = new javax.swing.JLabel();
        tf_emailAdres = new javax.swing.JTextField();
        jl_toernooiCodeNS = new javax.swing.JLabel();
        tf_toernooiCodeNS = new javax.swing.JTextField();
        jb_inschrijvenToernooi = new javax.swing.JButton();
        jb_toernooiZoeken = new javax.swing.JButton();
        jb_spelerZoeken = new javax.swing.JButton();
        jb_inschrijvenMasterclass = new javax.swing.JButton();
        jl_voornaamError = new javax.swing.JLabel();
        jl_achternaamError = new javax.swing.JLabel();
        jl_woonplaatsError = new javax.swing.JLabel();
        jl_postcodeError = new javax.swing.JLabel();
        jl_telefoonNummerError = new javax.swing.JLabel();
        jl_emailadresError = new javax.swing.JLabel();
        jl_toernooiCodeErrorNS = new javax.swing.JLabel();
        cb_betaald = new javax.swing.JCheckBox();
        test = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(364, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_voornaam.setText("Voornaam            :");
        getContentPane().add(jl_voornaam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tf_voornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_voornaamKeyReleased(evt);
            }
        });
        getContentPane().add(tf_voornaam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, -1));

        jl_achternaam.setText("Achternaam        :");
        getContentPane().add(jl_achternaam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        tf_achternaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_achternaamKeyReleased(evt);
            }
        });
        getContentPane().add(tf_achternaam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 90, -1));

        jl_adres.setText("Adres                  :");
        getContentPane().add(jl_adres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        tf_adres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_adresKeyReleased(evt);
            }
        });
        getContentPane().add(tf_adres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, -1));

        jl_postcode.setText("Postcode             :");
        getContentPane().add(jl_postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        tf_postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_postcodeKeyReleased(evt);
            }
        });
        getContentPane().add(tf_postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 90, -1));

        jl_woonplaats.setText("Woonplaats         :");
        getContentPane().add(jl_woonplaats, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        tf_woonplaats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_woonplaatsActionPerformed(evt);
            }
        });
        tf_woonplaats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_woonplaatsKeyReleased(evt);
            }
        });
        getContentPane().add(tf_woonplaats, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 90, -1));

        jl_telefoonNummer.setText("Telefoonnummer :");
        getContentPane().add(jl_telefoonNummer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        tf_telefoonNummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_telefoonNummerKeyReleased(evt);
            }
        });
        getContentPane().add(tf_telefoonNummer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, -1));

        jl_emailAdres.setText(" Emailadres          :");
        getContentPane().add(jl_emailAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, -1, -1));

        tf_emailAdres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emailAdresKeyReleased(evt);
            }
        });
        getContentPane().add(tf_emailAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 90, -1));

        jl_toernooiCodeNS.setText("Toernooi/master code      :");
        getContentPane().add(jl_toernooiCodeNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        getContentPane().add(tf_toernooiCodeNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 90, -1));

        jb_inschrijvenToernooi.setText("Inschrijven toernooi");
        jb_inschrijvenToernooi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_inschrijvenToernooiActionPerformed(evt);
            }
        });
        getContentPane().add(jb_inschrijvenToernooi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 296, 145, -1));

        jb_toernooiZoeken.setText("Toernooi zoeken");
        jb_toernooiZoeken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_toernooiZoekenActionPerformed(evt);
            }
        });
        getContentPane().add(jb_toernooiZoeken, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 325, -1, -1));

        jb_spelerZoeken.setText("Speler zoeken");
        jb_spelerZoeken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_spelerZoekenActionPerformed(evt);
            }
        });
        getContentPane().add(jb_spelerZoeken, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 296, 111, -1));

        jb_inschrijvenMasterclass.setText("Inschrijven Masterclass");
        jb_inschrijvenMasterclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_inschrijvenMasterclassActionPerformed(evt);
            }
        });
        getContentPane().add(jb_inschrijvenMasterclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, -1, -1));

        jl_voornaamError.setForeground(new java.awt.Color(255, 0, 0));
        jl_voornaamError.setText("Alleen letters toegestaan");
        getContentPane().add(jl_voornaamError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jl_achternaamError.setForeground(new java.awt.Color(255, 0, 0));
        jl_achternaamError.setText("Alleen letters toegestaan");
        getContentPane().add(jl_achternaamError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jl_woonplaatsError.setForeground(new java.awt.Color(255, 0, 0));
        jl_woonplaatsError.setText("Alleen letters toegestaan");
        getContentPane().add(jl_woonplaatsError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jl_postcodeError.setForeground(new java.awt.Color(255, 0, 0));
        jl_postcodeError.setText("Voorbeeld: 1234AB");
        getContentPane().add(jl_postcodeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jl_telefoonNummerError.setForeground(new java.awt.Color(255, 0, 0));
        jl_telefoonNummerError.setText("Vul een geldig telefoonnummer in");
        getContentPane().add(jl_telefoonNummerError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jl_emailadresError.setForeground(new java.awt.Color(255, 0, 0));
        jl_emailadresError.setText("Ongeldig email adres");
        getContentPane().add(jl_emailadresError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jl_toernooiCodeErrorNS.setForeground(new java.awt.Color(255, 0, 0));
        jl_toernooiCodeErrorNS.setText("Voer alleen cijfers in");
        getContentPane().add(jl_toernooiCodeErrorNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        cb_betaald.setText("Betaald");
        cb_betaald.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb_betaaldStateChanged(evt);
            }
        });
        cb_betaald.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_betaaldActionPerformed(evt);
            }
        });
        getContentPane().add(cb_betaald, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        test.setText("test");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });
        getContentPane().add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_woonplaatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_woonplaatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_woonplaatsActionPerformed

    private void tf_voornaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_voornaamKeyReleased
        String voornaam = tf_voornaam.getText();
        if (voornaam.matches("[^0-9]{0,20}")) {
            jl_voornaamError.setVisible(false);
        }
        else    {
            jl_voornaamError.setVisible(true);
        }   
    }//GEN-LAST:event_tf_voornaamKeyReleased

    private void tf_achternaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_achternaamKeyReleased
        String achternaam = tf_achternaam.getText();
        if (achternaam.matches("[^0-9]{0,20}")) {
            jl_achternaamError.setVisible(false);
            
        }
        else    {
            jl_achternaamError.setVisible(true);
        }
    }//GEN-LAST:event_tf_achternaamKeyReleased

    private void tf_adresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_adresKeyReleased

    }//GEN-LAST:event_tf_adresKeyReleased

    private void tf_woonplaatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_woonplaatsKeyReleased
        String woonplaats = tf_woonplaats.getText();
        if (woonplaats.matches("[^0-9]{0,45}")) {
            jl_woonplaatsError.setVisible(false);
            
        }
        else    {
            jl_woonplaatsError.setVisible(true);
        }
    }//GEN-LAST:event_tf_woonplaatsKeyReleased

    private void tf_postcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_postcodeKeyReleased
        String postcode = tf_postcode.getText();
        if (postcode.matches("[0-9]{4}[a-zA-Z]{2}")) {
            jl_postcodeError.setVisible(false);
            
        }
        else    {
            jl_postcodeError.setVisible(true);
        }
    }//GEN-LAST:event_tf_postcodeKeyReleased

    private void tf_telefoonNummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_telefoonNummerKeyReleased
        String telefoonNummer = tf_telefoonNummer.getText();
        if (telefoonNummer.matches("[0-9]{10}")) {
            jl_telefoonNummerError.setVisible(false);
            
        }
        else    {
            jl_telefoonNummerError.setVisible(true);
        }
    }//GEN-LAST:event_tf_telefoonNummerKeyReleased

    private void tf_emailAdresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emailAdresKeyReleased
                    String emailAdres = tf_emailAdres.getText();
        if (emailAdres.contains("@") && emailAdres.contains(".")) {
            jl_emailadresError.setVisible(false);
                  }
        else    {
            jl_emailadresError.setVisible(true);
        }
    }//GEN-LAST:event_tf_emailAdresKeyReleased

    private void jb_inschrijvenToernooiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_inschrijvenToernooiActionPerformed
        if(betaaldBoolean) {
            
        Persoon nieuwePersoon = new Persoon();
        
        String voornaam = tf_voornaam.getText();
        String achternaam = tf_achternaam.getText();
        String adres = tf_adres.getText();
        String woonplaats = tf_woonplaats.getText();
        String postcode = tf_postcode.getText();
        String telefoonNummer = tf_telefoonNummer.getText();
        String emailAdres = tf_emailAdres.getText();
        int telefoonNummerInt = Integer.parseInt(telefoonNummer);
        
        nieuwePersoon.persoonToevoegen(voornaam, achternaam, adres, woonplaats, postcode, telefoonNummerInt, emailAdres);
        JOptionPane.showMessageDialog(rootPane, "Toevoegen voltooid!");
        }
        else if (!betaaldBoolean){
            JOptionPane.showMessageDialog(rootPane, "Er is nog niet betaald!");
        }
    }//GEN-LAST:event_jb_inschrijvenToernooiActionPerformed

    private void jb_spelerZoekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_spelerZoekenActionPerformed
        SpelerZoeken spelerZoeken = new SpelerZoeken();
        spelerZoeken.setVisible(true);
    }//GEN-LAST:event_jb_spelerZoekenActionPerformed

    private void jb_toernooiZoekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_toernooiZoekenActionPerformed
        Toernooi toernooiZoeken = new Toernooi();
        toernooiZoeken.setVisible(true);
    }//GEN-LAST:event_jb_toernooiZoekenActionPerformed

    private void cb_betaaldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_betaaldActionPerformed
        if(cb_betaald.isSelected()) {
            betaaldBoolean = true;
        }
        else
            betaaldBoolean = false;
            
    }//GEN-LAST:event_cb_betaaldActionPerformed

    private void cb_betaaldStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb_betaaldStateChanged
        
        
    }//GEN-LAST:event_cb_betaaldStateChanged

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        System.out.println(betaaldBoolean);
    }//GEN-LAST:event_testActionPerformed

    private void jb_inschrijvenMasterclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_inschrijvenMasterclassActionPerformed
        if(betaaldBoolean) {
            
        Masterclass inschrijvenM = new Masterclass();
        Persoon nieuwePersoon = new Persoon();
        
        String voornaam = tf_voornaam.getText();
        String achternaam = tf_achternaam.getText();
        String adres = tf_adres.getText();
        String woonplaats = tf_woonplaats.getText();
        String postcode = tf_postcode.getText();
        String telefoonNummer = tf_telefoonNummer.getText();
        String emailAdres = tf_emailAdres.getText();
        int telefoonNummerInt = Integer.parseInt(telefoonNummer);
        String codeString = tf_toernooiCodeNS.getText();
        int codeInt = Integer.parseInt(codeString);

        nieuwePersoon.persoonToevoegen(voornaam, achternaam, adres, woonplaats, postcode, telefoonNummerInt, emailAdres);
        inschrijvenM.inschrijvenMasterclass(codeInt, voornaam, achternaam );
        JOptionPane.showMessageDialog(rootPane, "Toevoegen voltooid!");
        }
        else if (!betaaldBoolean){
            JOptionPane.showMessageDialog(rootPane, "Er is nog niet betaald!");
        }
    }//GEN-LAST:event_jb_inschrijvenMasterclassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NieuweSpeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NieuweSpeler().setVisible(true);
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_betaald;
    private javax.swing.JButton jb_inschrijvenMasterclass;
    private javax.swing.JButton jb_inschrijvenToernooi;
    private javax.swing.JButton jb_spelerZoeken;
    private javax.swing.JButton jb_toernooiZoeken;
    private javax.swing.JLabel jl_achternaam;
    private javax.swing.JLabel jl_achternaamError;
    private javax.swing.JLabel jl_adres;
    private javax.swing.JLabel jl_emailAdres;
    private javax.swing.JLabel jl_emailadresError;
    private javax.swing.JLabel jl_postcode;
    private javax.swing.JLabel jl_postcodeError;
    private javax.swing.JLabel jl_telefoonNummer;
    private javax.swing.JLabel jl_telefoonNummerError;
    private javax.swing.JLabel jl_toernooiCodeErrorNS;
    private javax.swing.JLabel jl_toernooiCodeNS;
    private javax.swing.JLabel jl_voornaam;
    private javax.swing.JLabel jl_voornaamError;
    private javax.swing.JLabel jl_woonplaats;
    private javax.swing.JLabel jl_woonplaatsError;
    private javax.swing.JButton test;
    private javax.swing.JTextField tf_achternaam;
    private javax.swing.JTextField tf_adres;
    private javax.swing.JTextField tf_emailAdres;
    private javax.swing.JTextField tf_postcode;
    private javax.swing.JTextField tf_telefoonNummer;
    private javax.swing.JTextField tf_toernooiCodeNS;
    private javax.swing.JTextField tf_voornaam;
    private javax.swing.JTextField tf_woonplaats;
    // End of variables declaration//GEN-END:variables
}
