/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouse;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gebruiker
 */
public class rating_op_af_overzicht extends javax.swing.JFrame {

    /**
     * Creates new form rating_op_af_overzicht
     */

    private Connection connection = DatabaseConnectie.getConnection();

    public rating_op_af_overzicht() {
        initComponents();
        vulOverzichtTabel();
        this.setLocationRelativeTo(null);
    }
    
    private void vulOverzichtTabel(){
        
        try {
            DefaultTableModel datamodel = createSpelerModel();
            this.j_overzichttabel.setModel(datamodel);

            String query = "SELECT persoon_code, voornaam, achternaam, tafel_code, toernooi_code, ronde_code, rating_op_af " +
                           "FROM toernooi join tafel_deelnemers on t_code = toernooi_code " +
                                         "join persoon pe on p_code = persoon_code " +
                           "WHERE tafel_winnaar = persoon_code " +
                            "AND voornaam like ? AND achternaam like ? AND toernooi_code LIKE ?;";

            PreparedStatement statement = connection.prepareStatement(query);

            
            statement.setString(3, getZoekToernooiCode());
            statement.setString(2, getZoekTermAchternaam());
            statement.setString(1, getZoekTermVoornaam());
            
            ResultSet results = statement.executeQuery();

            while (results.next()) {
                String spelercode = results.getString("persoon_code");
                String voornaam = results.getString("voornaam");
                String achternaam = results.getString("achternaam");
                String tafel_code = results.getString("tafel_code");
                String toernooi_code = results.getString("toernooi_code");
                String ronde_code = results.getString("ronde_code");
                String rating_op_af = results.getString("rating_op_af");
                Object[] rij = {spelercode, voornaam, achternaam, tafel_code, toernooi_code, ronde_code, rating_op_af};
                datamodel.addRow(rij);

            }

            this.j_overzichttabel.setModel(datamodel);
        } catch (SQLException ex) {
            Logger.getLogger(SpelerZoeken.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private String getZoekToernooiCode() {
        String text2 = t_t_code.getText();
        if (text2.length() == 0) {
            return "%";
        } else {
            return "%" + text2 + "%";
        }
    }
    
    private String getZoekTermAchternaam() {
        String text2 = t_achternaam.getText();
        if (text2.length() == 0) {
            return "%";
        } else {
            return "%" + text2 + "%";
        }
    }
    
    private String getZoekTermVoornaam() {
        String text2 = t_voornaam.getText();
        if (text2.length() == 0) {
            return "%";
        } else {
            return "%" + text2 + "%";
        }
    }
    
      private DefaultTableModel createSpelerModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("speler code");
        model.addColumn("voornaam");
        model.addColumn("achternaam");
        model.addColumn("tafel_code");
        model.addColumn("toernooi_code");
        model.addColumn("ronde_code");
        model.addColumn("rating_op_af");
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        j_overzichttabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t_t_code = new javax.swing.JTextField();
        l_voornaam = new javax.swing.JLabel();
        t_voornaam = new javax.swing.JTextField();
        l_achternaam = new javax.swing.JLabel();
        t_achternaam = new javax.swing.JTextField();
        b_sluit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j_overzichttabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(j_overzichttabel);

        jLabel1.setText("toernooicode:");

        t_t_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_t_codeKeyReleased(evt);
            }
        });

        l_voornaam.setText("voornaam:");

        t_voornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_voornaamKeyReleased(evt);
            }
        });

        l_achternaam.setText("achternaam:");

        t_achternaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_achternaamKeyReleased(evt);
            }
        });

        b_sluit.setText("Sluit");
        b_sluit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sluitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_t_code, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_voornaam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_achternaam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_achternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_sluit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t_t_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_voornaam)
                    .addComponent(t_voornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_achternaam)
                    .addComponent(t_achternaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_sluit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_achternaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_achternaamKeyReleased
        this.vulOverzichtTabel();
    }//GEN-LAST:event_t_achternaamKeyReleased

    private void t_voornaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_voornaamKeyReleased
        this.vulOverzichtTabel();
    }//GEN-LAST:event_t_voornaamKeyReleased

    private void t_t_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_t_codeKeyReleased
        this.vulOverzichtTabel();
    }//GEN-LAST:event_t_t_codeKeyReleased

    private void b_sluitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sluitActionPerformed
        this.dispose();
    }//GEN-LAST:event_b_sluitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rating_op_af_overzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rating_op_af_overzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rating_op_af_overzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rating_op_af_overzicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new rating_op_af_overzicht().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_sluit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable j_overzichttabel;
    private javax.swing.JLabel l_achternaam;
    private javax.swing.JLabel l_voornaam;
    private javax.swing.JTextField t_achternaam;
    private javax.swing.JTextField t_t_code;
    private javax.swing.JTextField t_voornaam;
    // End of variables declaration//GEN-END:variables
}
